# RDS PostgreSQL, provisioned to the same DBRE standards the local Docker
# path applies via SQL -- the difference is *where* each standard is
# enforced (see docs/local-vs-aws.md):
#
#   - connection/session timeouts -> SQL (ALTER DATABASE ...), same in both modes
#   - shared_preload_libraries, log_* -> DB Parameter Group here; postgres
#     command-line flags in docker-compose locally
#   - Multi-AZ, backup retention, deletion protection, enhanced monitoring,
#     encryption -> only meaningful in AWS mode; there is no local equivalent,
#     which is exactly why policy (policies/environments/prod.yaml) requires
#     spec.platform: aws for production.

locals {
  identifier             = "${var.name}-${var.environment}"
  parameter_group_family = "postgres${split(".", var.engine_version)[0]}"

  baseline_parameters = {
    max_connections = tostring(var.connection_limit + 20)
  }
  merged_parameters = merge(local.baseline_parameters, var.cluster_parameters)
}

# ---------------------------------------------------------------------------
# Credentials: the master password is generated by Terraform and stored only
# in Secrets Manager -- it is never a plain Terraform variable, never in
# .tfvars, and never printed in plan/apply output (see the `sensitive`
# marking on the random_password resource and on outputs.tf).
# ---------------------------------------------------------------------------
resource "random_password" "master" {
  length  = 32
  special = false # avoid characters that need shell/URL escaping downstream
}

resource "aws_secretsmanager_secret" "master" {
  name        = "dbre-platform/${local.identifier}/master-credentials"
  description = "RDS master credentials for ${local.identifier}, managed by dbre-platform Terraform."
  kms_key_id  = var.kms_key_id != "" ? var.kms_key_id : null
  tags        = var.tags
}

resource "aws_secretsmanager_secret_version" "master" {
  secret_id     = aws_secretsmanager_secret.master.id
  secret_string = jsonencode({
    username = "dbre_admin"
    password = random_password.master.result
    engine   = "postgres"
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = replace(var.name, "-", "_")
  })
}

# ---------------------------------------------------------------------------
# Networking: security group scoped to exactly the callers that need it.
# No 0.0.0.0/0 ingress is possible from this module's variables alone -- see
# variables.allowed_cidr_blocks, which defaults to empty.
# ---------------------------------------------------------------------------
resource "aws_security_group" "this" {
  name        = "dbre-${local.identifier}"
  description = "PostgreSQL access for ${local.identifier}"
  vpc_id      = var.vpc_id
  tags        = var.tags
}

resource "aws_security_group_rule" "ingress_security_groups" {
  count                    = length(var.allowed_security_group_ids)
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.this.id
  source_security_group_id = var.allowed_security_group_ids[count.index]
  description              = "App tier access"
}

resource "aws_security_group_rule" "ingress_cidrs" {
  count             = length(var.allowed_cidr_blocks) > 0 ? 1 : 0
  type              = "ingress"
  from_port         = 5432
  to_port           = 5432
  protocol          = "tcp"
  security_group_id = aws_security_group.this.id
  cidr_blocks       = var.allowed_cidr_blocks
  description       = "Explicit CIDR access (should be empty in production)"
}

# RDS does not initiate outbound connections for normal operation --
# backups, snapshots, and control-plane traffic all run over AWS-managed
# infrastructure outside this security group. No egress rule is created by
# default. If a specific integration (e.g. the aws_s3 extension, an
# external replication target) genuinely needs outbound access, set
# egress_cidr_blocks in the environment's tfvars rather than reopening
# 0.0.0.0/0 on all ports here.
resource "aws_security_group_rule" "egress_scoped" {
  count             = length(var.egress_cidr_blocks) > 0 ? 1 : 0
  type              = "egress"
  from_port         = 443
  to_port           = 443
  protocol          = "tcp"
  security_group_id = aws_security_group.this.id
  cidr_blocks       = var.egress_cidr_blocks
  description       = "Explicit outbound HTTPS access (opt-in, empty by default)"
}

resource "aws_db_subnet_group" "this" {
  name       = "dbre-${local.identifier}"
  subnet_ids = var.subnet_ids
  tags       = var.tags
}

# ---------------------------------------------------------------------------
# DB Parameter Group: cluster-level GUCs, generated from the same standards
# module the local Docker path uses (build_cluster_parameters), so the two
# modes never drift out of sync with each other.
# ---------------------------------------------------------------------------
resource "aws_db_parameter_group" "this" {
  name   = "dbre-${local.identifier}"
  family = local.parameter_group_family
  tags   = var.tags

  dynamic "parameter" {
    for_each = local.merged_parameters
    content {
      name         = parameter.key
      value        = parameter.value
      apply_method = contains(["shared_preload_libraries", "max_connections"], parameter.key) ? "pending-reboot" : "immediate"
    }
  }
}

# ---------------------------------------------------------------------------
# Enhanced monitoring IAM role (only created when requested).
# ---------------------------------------------------------------------------
data "aws_iam_policy_document" "monitoring_assume_role" {
  count = var.enhanced_monitoring ? 1 : 0
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "enhanced_monitoring" {
  count              = var.enhanced_monitoring ? 1 : 0
  name               = "dbre-${local.identifier}-rds-monitoring"
  assume_role_policy = data.aws_iam_policy_document.monitoring_assume_role[0].json
  tags               = var.tags
}

resource "aws_iam_role_policy_attachment" "enhanced_monitoring" {
  count      = var.enhanced_monitoring ? 1 : 0
  role       = aws_iam_role.enhanced_monitoring[0].name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

# ---------------------------------------------------------------------------
# The database instance itself.
# ---------------------------------------------------------------------------
resource "aws_db_instance" "this" {
  identifier     = local.identifier
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage_gb
  max_allocated_storage = var.max_allocated_storage_gb > 0 ? var.max_allocated_storage_gb : null
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = var.kms_key_id != "" ? var.kms_key_id : null

  db_name  = replace(var.name, "-", "_")
  username = "dbre_admin"
  password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]
  publicly_accessible    = false

  # Lets individual database users authenticate via short-lived IAM tokens
  # instead of the shared master password, without changing how the master
  # user itself connects. Purely additive -- see docs/decisions/0002 family
  # for why the master credential flow stays password-based.
  iam_database_authentication_enabled = true

  parameter_group_name = aws_db_parameter_group.this.name

  multi_az                  = var.multi_az
  backup_retention_period   = var.backup_retention_days
  backup_window             = "03:00-04:00"
  maintenance_window        = "sun:04:30-sun:05:30"
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.environment != "prod"
  final_snapshot_identifier = var.environment == "prod" ? "${local.identifier}-final" : null
  copy_tags_to_snapshot     = true

  monitoring_interval = var.enhanced_monitoring ? 60 : 0
  monitoring_role_arn = var.enhanced_monitoring ? aws_iam_role.enhanced_monitoring[0].arn : null

  performance_insights_enabled          = var.performance_insights_enabled
  performance_insights_retention_period = var.performance_insights_enabled ? 7 : null
  performance_insights_kms_key_id       = var.performance_insights_enabled && var.kms_key_id != "" ? var.kms_key_id : null

  auto_minor_version_upgrade = var.environment != "prod"
  apply_immediately          = var.environment != "prod"

  tags = var.tags

  lifecycle {
    prevent_destroy = false # the platform's own guardrail is policy + deletion_protection, not a TF lifecycle block a plan could silently hit
    ignore_changes  = [password] # rotated out-of-band via Secrets Manager, not by re-running terraform apply
  }
}

# ---------------------------------------------------------------------------
# Baseline CloudWatch alarms. This is intentionally a small, fixed set of
# infrastructure-level signals (the things only AWS can tell you) -- the
# richer, vendor-neutral SLO/query-based observability model lives in
# dbre_platform.observability and monitoring/, and is what actually backs
# the platform's SLO framework. See docs/slo-framework.md.
# ---------------------------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "high_cpu" {
  alarm_name          = "dbre-${local.identifier}-high-cpu"
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  comparison_operator = "GreaterThanThreshold"
  threshold           = 85
  period              = 300
  evaluation_periods  = 3
  dimensions          = { DBInstanceIdentifier = aws_db_instance.this.id }
  tags                = var.tags
}

resource "aws_cloudwatch_metric_alarm" "low_free_storage" {
  alarm_name          = "dbre-${local.identifier}-low-free-storage"
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  statistic           = "Average"
  comparison_operator = "LessThanThreshold"
  threshold           = 5 * 1024 * 1024 * 1024 # 5 GiB, bytes
  period              = 300
  evaluation_periods  = 2
  dimensions          = { DBInstanceIdentifier = aws_db_instance.this.id }
  tags                = var.tags
}

resource "aws_cloudwatch_metric_alarm" "high_connections" {
  alarm_name          = "dbre-${local.identifier}-high-connections"
  namespace           = "AWS/RDS"
  metric_name         = "DatabaseConnections"
  statistic           = "Average"
  comparison_operator = "GreaterThanThreshold"
  threshold           = var.connection_limit * 0.9
  period              = 300
  evaluation_periods  = 3
  dimensions          = { DBInstanceIdentifier = aws_db_instance.this.id }
  tags                = var.tags
}
