#!/usr/bin/env python3
"""Regenerate k8s/reference/*.yaml from build_cluster_manifest.

These are generated output, not hand-maintained -- they are exactly what
``dbre request provision --mode k3s`` applies for two example requests, so
they can never drift from ``dbre_platform.provisioning.k3s``. CI
(``.github/workflows/k8s-validate.yml``) fails if the committed files are
stale. Run this whenever ``build_cluster_manifest`` changes.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from dbre_platform.config.models import DatabaseRequest
from dbre_platform.provisioning.k3s import build_cluster_manifest

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "k8s" / "reference"

_HEADER = (
    "# Generated by dbre_platform.provisioning.k3s.build_cluster_manifest -- do not hand-edit.\n"
    "# Regenerate: `make k8s-reference`. This is exactly what "
    "`dbre request provision --mode k3s` applies.\n"
)

_DEV = {
    "metadata": {
        "name": "catalog-api",
        "environment": "dev",
        "owner": "catalog-team",
        "cost_center": "CC-1001",
        "data_classification": "internal",
    },
    "spec": {
        "platform": "k3s",
        "namespace": "dbre",
        "storage_gb": 20,
        "instances": 1,
        "extensions": ["pg_stat_statements"],
        "resources": {
            "cpu_request": "100m",
            "memory_request": "256Mi",
            "cpu_limit": "1",
            "memory_limit": "512Mi",
        },
    },
}

_PROD = {
    "metadata": {
        "name": "orders-api",
        "environment": "prod",
        "owner": "payments-team",
        "cost_center": "CC-4471",
        "data_classification": "confidential",
    },
    "spec": {
        "platform": "k3s",
        "namespace": "dbre",
        "storage_gb": 100,
        "instances": 3,
        "multi_az": True,
        "backup_retention_days": 30,
        "deletion_protection": True,
        "enhanced_monitoring": True,
        "connection_limit": 200,
        "extensions": ["pg_stat_statements", "pgaudit", "auto_explain"],
        "tags": {"team-slack-channel": "#payments-oncall"},
        "approvals": [{"approver": "jane-doe", "ticket": "CHG-20441", "approved_at": "2026-01-15"}],
        "slo": {
            "availability_target": 0.999,
            "latency_p99_ms": 150,
            "backup_rpo_hours": 12,
            "recovery_rto_hours": 2,
        },
        "resources": {
            "cpu_request": "500m",
            "memory_request": "1Gi",
            "cpu_limit": "2",
            "memory_limit": "4Gi",
        },
    },
}


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for filename, doc in (("dev-cluster.yaml", _DEV), ("prod-cluster.yaml", _PROD)):
        manifest = build_cluster_manifest(DatabaseRequest.model_validate(doc))
        (OUT_DIR / filename).write_text(_HEADER + yaml.dump(manifest, sort_keys=False))
        print(f"wrote {(OUT_DIR / filename).relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
